[package]
name = "brust"
version = "0.1.0"
authors = ["Thomas Campistron <irevoire@hotmail.fr>"]
edition = "2018"

[dependencies]
tokio = { version = "1", features = ["full"] }
serenity = { version = "0.10.2", features = ["collector"] }
select = "*"
kankyo = "*"
rand = { version = "0.8.0", features = ["small_rng"] }
reqwest = { version = "*", features = ["json"] }
serde_json = "*"
anyhow = "*"
